### ISSUE TITLE
Adaptar para o layout responsivo as imagens nos testes 2 e 3

### ISSUE THREAD

**Issue by rprata** [rprata/popeteste#4]
Adaptar para o layout responsivo as imagens nos testes 2 e 3

**Comment by raulsenaferreira** [comment]
@rprata fatie as imagens pra mim e coloque em uma pasta com os nomes em ordem, que eu adapto elas para um layout responsivo.
Exemplo: 
imagens da index2.html -> 
parte2/img1.png 
parte2/img2.png
...
E assim por diante, suba aqui pro git que eu dou checkout delas.

**Comment by rprata** [comment]
@raulsenaferreira Fiz um commit separando as imagens como pediu

**Comment by raulsenaferreira** [comment]
Falta apenas ajeitar algumas coisinhas no CSS mas já está responsivo, se ajeitando na tela
